### ISSUE TITLE
If OTP is activated, ask for it after login

### ISSUE THREAD

**Issue by nicolas-besnard** [jeremyevans/rodauth#100]
On most website, when I log in and OTP is activated, I'm ask right away to enter it.

Using Rodauth, the OTP is only asked when accessing a protected resource.

I'm new in the Rodauth and Roda environment, is there a way to reproduce that?

**Comment by jeremyevans** [comment]
If you want to reproduce that, you can probably add this near the top of the Roda routing tree (probably after running assets/public routes):

```ruby
  
  if rodauth.logged_in? && rodauth.two_factor_authentication_setup? &&  !rodauth.two_factor_authenticated?`
    rodauth.require_two_factor_authenticated
  end
```

Hopefully that will do what you want.  If not, please explain in more detail what you want.

**Comment by nicolas-besnard** [comment]
I'm using [janko/rodauth-rails][1] and I'm using the controller approach where I define a `require_authentication` method and use a callback in my controller.

```rb
# applicaton_controller.rb
def require_authenticattion
  if !rodauth.logged_in?
    return rodauth.require_authentication
  end

  if rodauth.logged_in? && rodauth.two_factor_authentication_setup? && !rodauth.two_factor_authenticated?
    return rodauth.require_two_factor_authenticated
  end
end

# other_controller.rb

class OtherController < ApplicationController
  before_action :require_authentication
end
```

So everything is working when trying to access a protected route: the user need to enter login / password then OTP.

However, if I have a login form in my home page (which does not require authentication), when the user log in, and go back to the home page, he's not asked for OTP (where I'd like him to enter it right after the login / password match).

In most website, I'm asked for OTP right after the login / password combo match, and I'm not considered "logged in" until login / password + OTP is right

[1]: https://github.com/janko/rodauth-rails

**Comment by janko** [comment]
@nicolas-besnard You should put the code Jeremy posted in your Rodauth app, inside the `route` block, which gets executed before every route in your app. So it will run regardless of whether login redirects to a page that requires or doesn't require authentication.

Putting it in your `#require_authentication` hook of course won't do what you want, because as you said, you're running this code only for routes for which you want to require authentication.

**Comment by nicolas-besnard** [comment]
@janko It's indeed working, thank you! I'll close this issue :)

The documentation is really "tech" oriented, and I've to read the source code to understand some option.

Would you accept a PR to help people reproduce "common" behavior?

**Comment by janko** [comment]
I have prepared some common how-to guides locally which I'm planning to PR so that we can add them to the Rodauth website, but I haven't found time to finalize that effort. So I think it makes sense that you start with this one 😉
