### ISSUE TITLE
Mongoid support

### ISSUE THREAD

**Issue by HLFH** [jeremyevans/rodauth#111]
It would be great to have Mongoid support.

**Comment by jeremyevans** [comment]
I believe all of Rodauth's database access is through code that can be using Rodauth's configuration methods.  So someone could theoretically add Mongoid support using the configuration methods, without changes to Rodauth itself.

There is no plans for native Rodauth support for MongoDB, now or in the future, as the existing database access depends heavily on Sequel, which is only for SQL databases.
