### ISSUE TITLE
HTTP Basic auth failing with curl

### ISSUE THREAD

**Issue by TiagoCardoso1983** [jeremyevans/rodauth#13]
[The regexp is somehow not parsing out the baisc token when coming from cURL](https://github.com/jeremyevans/rodauth/blob/master/lib/rodauth/features/http_basic_auth.rb#L11).

* First, it seems that the newline (which I added because it was appended on the rack test helpers) may or may not be there (curl doesn't). 
* That messes up the `\z` (if removed, it all works). Do you have any idea why this happens?

**Comment by TiagoCardoso1983** [comment]
Rails splits by `" "` (https://github.com/rails/rails/blob/master/actionpack/lib/action_controller/metal/http_authentication.rb#L113-L119). 
Rack does the same (https://github.com/rack/rack/blob/master/lib/rack/auth/abstract/request.rb#L23-L25). 

Maybe it was a bad idea to use the regex here in the first place.

**Comment by jeremyevans** [comment]
You can try switching from `\n\z` to `\Z`, which will ignore a trailing newline if present, but not require one.  Alternatively, you could split the string on the space, then check if the first part is `Basic`.

**Comment by TiagoCardoso1983** [comment]
I'll opt for the second approach, as I haven't seen any other type of implementation.

**Comment by jeremyevans** [comment]
Closing as the fix is being track in #16.
