### ISSUE TITLE
botnet feeding email addresses into /create-account

### ISSUE THREAD

**Issue by plujon** [jeremyevans/rodauth#130]
My server IP was recently blacklisted or blocked by a few mail providers (outlook, gmail, and yahoo).

After digging into it, I discovered what appears to be a botnet submitting various email addresses into the form at /create-account .

How irritating.

I disabled account creation on my site until this is further diagnosed.

    # :create_account,
    # :verify_account,

I can provide more information shortly, but I'm filing this ASAP to give Jeremy a heads up in case this is a phenomenon he hasn't seen before.  Perhaps a CAPTCHA is in order.

**Comment by janko** [comment]
I'm wondering whether using [Truemail](https://github.com/truemail-rb/truemail) for email validation would help here, which offers MX and SMTP validation. Not sure if these emails existed.

**Comment by plujon** [comment]
I think many if not most of the emails are legit (or were at some point -- some have since disappeared, as evidenced by a few "undeliverables" in mail.log).  An unusually high number use ALLCAPS@GMAIL.COM, something no real human does...

In addition to disabling the account creation page, I have also blocked tor exit nodes (https://check.torproject.org/torbulkexitlist), as a large number of the submissions came from domains with "tor" in them.

**Comment by jeremyevans** [comment]
This can happen with pretty much any site, and isn't specific to Rodauth.  A CAPTCHA during account creation can help mitigate the issue, at the expense of normal user experience. I could consider a feature for using a CAPTCHA, but I'm also a little hesitant to add more optional dependencies.  I suppose it would depend on the implementation.  It's already possible to add your own CAPTCHA using create_account_additional_form_tags and before hooks.

As I don't think this is a bug in Rodauth, I'm going to close this now.

**Comment by plujon** [comment]
I agree that this can happen with pretty much any site; I'd just not seen bots used in this way before.

It is unclear whether the goal of the bots is to deliver email spam that the bots control, to try and create credentials for later use, or just to cause general mayhem.  If t's the latter, any web form that takes an email and sends a confirmation/verification message to that email is a target.  Fortunately, the bots I've encountered are pretty slow, perhaps to avoid detection.
