### ISSUE TITLE
how to use other column to  register and login

### ISSUE THREAD

**Issue by nyrf** [jeremyevans/rodauth#143]
In our application, we don't need email, we want to use username or mobile to register and login, thanks.

**Comment by jeremyevans** [comment]
Please review Rodauth's documentation: http://rodauth.jeremyevans.net/documentation.html

If you still have questions, please ask on the Rodauth Google Group.  GitHub Issues should only be used for bug reports, per the contribution guidelines.

As a hint, you probably want to use the `login_column` configuration method.
