### ISSUE TITLE
BCrypt cost for application

### ISSUE THREAD

**Issue by jswright61** [jeremyevans/rodauth#156]
I would like to know how to set a default cost for BCrypt hashes. Currently the system default is used. I would like to set a custom default for the application.

Currently the cost is set in lib/rodauth/features/login_password_requirements_base.rb. I would like to set an application default cost in the initializer and have Rodauth use that in preference to the BCrypt::Engine::DEFAULT_COST if it exists.

**Comment by jeremyevans** [comment]
You can use the `password_hash_cost` configuration method to set the cost (see http://rodauth.jeremyevans.net/rdoc/files/doc/login_password_requirements_base_rdoc.html).

As explained in the contribution guidelines, GitHub Issues should only be used to file bugs in the library.  Please use the Rodauth Google Group if you have questions about Rodauth.
