### ISSUE TITLE
Citext can't be found

### ISSUE THREAD

**Issue by Bdoom** [jeremyevans/rodauth#173]
Not sure what I'm doing wrong here but it looks like it's not working as expected:

![image](https://user-images.githubusercontent.com/1284431/125206172-bc0c0780-e253-11eb-9d0a-10455443cfc1.png)

**Comment by jeremyevans** [comment]
Looks like you missed this part of the setup instructions: http://rodauth.jeremyevans.net/rdoc/files/README_rdoc.html#label-Load+extensions

If you have additional issues setting up Rodauth, please ask on the rodauth Google Group.  As mentioned in the contribution guidelines, GitHub Issues should only be used to report bugs in the library.
