### ISSUE TITLE
"The JSON API uses the POST method for all requests"

### ISSUE THREAD

**Issue by ayghor** [jeremyevans/rodauth#19]
EHLO,

i am considering Roda and Rodauth for my current project and just stumbled this "The JSON API uses the POST method for all requests". why did you make it that way? is it possible to enable teh GET?

i googled around for a whiel and could only find people saying "this is bad design since POST isnt cacheable" and stuff.

<3

**Comment by jeremyevans** [comment]
Rodauth's JSON API is only for logging in and making changes, there is very little reason to use GET for those (you generally wouldn't want to cache them).  You can certainly use GET and other methods in your Roda app.

In the future, as mentioned in the contribution guidelines, please ask similar questions on IRC or the Google Group.  GitHub Issues should only be used to report bugs in the library.

**Comment by ayghor** [comment]
ok! ty and sry!
