### ISSUE TITLE
Change response body

### ISSUE THREAD

**Issue by randsina** [jeremyevans/rodauth#20]
Hi. I want to change response body to put one more token on login and create_account.
I use JWT and I found one example do it: overriding method '/login'.
Is there way to do it simpler?

**Comment by jeremyevans** [comment]
I think this should work inside the rodauth configuration block:

```ruby
update_session
  super
  session[:some_token] = some_value
end
```

This will affect all ways of logging in (whenever the account_id is set in the session).

The JWT just encodes the session information.  To be pedantic, the JWT is not returned in the response body, it's returned in the response Authorization header.

Note as this is a question about how to use Rodauth, and not reporting a bug in Rodauth.  Per the contribution guidelines, please ask similar questions in the future on the Google Group or IRC channel.
