### ISSUE TITLE
The demo site and docs are served over HTTP not HTTPS

### ISSUE THREAD

**Issue by nickjj** [jeremyevans/rodauth#220]
Hi,

At the time of making this issue http://rodauth-demo.jeremyevans.net/ and http://rodauth.jeremyevans.net/ are being served over HTTP and are linked in the docs like this. Trying to visit the HTTPS version of your site resulted in an insecure certificate warning.

Given the nature of this library and general best practices it would be worth adding HTTPS support to your site. Without it, anyone who wants to demo this library with their own email address would result in the password being sent over the internet in plain text.

**Comment by jeremyevans** [comment]
The demo site is designed to be a demo, and doesn't send email, so you can use whatever test email addresses you like.  It's currently served on a free Heroku plan, which doesn't support SSL.  I'm not willing to pay money every month just for SSL support.
