### ISSUE TITLE
Facebook example: authorization header and super()

### ISSUE THREAD

**Issue by ayghor** [jeremyevans/rodauth#23]
i think that teh example could say that teh facebook login returns a regular `Authorization: ` header. This way it is clear that we can just make a secondary rodauth config, just for facebook login, and then use teh plain rodauth features without this config interference, which is a major win to support login from multiple services.

also, there is a `super()` on `account_from_login` block. i must admit that i never tested. =OP

wat do u think?

**Comment by jeremyevans** [comment]
I don't want to have the example use two separate concerns.  We have a separate example for using multiple configurations.  If you just have facebook login and don't support other methods of authentication, multiple configurations wouldn't make sense.

The super in account_from_login should probably go.  I'll restructure things to make the facebook example more similar to the LDAP example.
