### ISSUE TITLE
JWT CORS: Mixing Strings and RexExp's in Array

### ISSUE THREAD

**Issue by benoror** [jeremyevans/rodauth#249]
Hey! I have a particular scenario while using a provider such as [Vercel](https://vercel.com/) which generates "Preview" deployments with random hashes inside the URL. Therefore I need to add a RegExp to `jwt_cors_allow_origin`, additionally to existing Strings, but I get the following error:

```
NoMethodError (undefined method `length' for /https:\/\/spoint-.*-benoror.vercel.app/:Regexp):
```

I am assuming the Array only accepts Strings, not RexExp's. Any workaround would be greatly appreciated!

**Comment by jeremyevans** [comment]
`jwt_cors_allow_origin` does not support an array containing regexps.  You can use an array of strings, or a single regexp.  Maybe you want `jwt_cors_allow_origin Regexp.union(array_of_strings_and_or_regexps)`?

**Comment by benoror** [comment]
Good idea! Gonna give it a shot!

And besides that, quickest issue reply ever, thanks! appreciate your work!

**Comment by benoror** [comment]
`Regexp.union` worked beautifully as a drop-in. Thanks again!
