### ISSUE TITLE
Admin activation: email_to & verify_account_email_body not overriding

### ISSUE THREAD

**Issue by benoror** [jeremyevans/rodauth#251]
Following the [admin_activation.rdoc](https://rodauth.jeremyevans.net/rdoc/files/doc/guides/admin_activation_rdoc.html) guide I noticed that this two snippets of code won't work with latest release(`2.25.0`)

This one fails to override the `email_to`:

```ruby
  # Send account verification email to the admin
  email_to do
    if account[account_status_column] == account_unverified_status_value
      "admin@myapp.com"
    else
      super()
    end
  end
```

This fails to override email's body
```ruby
  verify_account_email_body do
    "The user #{account[login_column]} has created an account. Click here to approve it: #{verify_account_email_link}."
  end
```

Thanks!

**Comment by janko** [comment]
Are you using rodauth-rails? There a custom mailer is generated on installation, which doesn't use these methods.

**Comment by benoror** [comment]
@janko that was it 🤦 thanks a bunch dude!
