### ISSUE TITLE
PG::UndefinedTable: ERROR: relation "account_activity_times" does not exist

### ISSUE THREAD

**Issue by a14guguliye** [jeremyevans/rodauth#253]
Hello,
While following the tutorial of rodauth i face below error
No matter how hard i try, i can not solve it 
can someone please help?
`PG::UndefinedTable: ERROR: relation "account_activity_times" does not exist
LINE 1: ..._activity_at", "last_login_at", "expired_at" FROM "account_a...
   rodauth.load_memory # autologin remembered users

    r.rodauth # route rodauth requests

    rodauth.oauth_applications
    rodauth.openid_configuration
`

**Comment by jeremyevans** [comment]
You need to create the tables in the database before you use Rodauth.  Rodauth does not do that for you.

You should review:

* https://github.com/jeremyevans/rodauth#label-PostgreSQL+Database+Setup
* https://github.com/jeremyevans/rodauth#label-Creating+tables

If you have questions regarding either, please create a discussion post.  Only create an issue to report a bug in the library.
