### ISSUE TITLE
Internal request `verify_account` with `account_login` does not work

### ISSUE THREAD

**Issue by mainameiz** [jeremyevans/rodauth#257]
Hi, Jeremy!

Seems like this part of rodauth does not work
![изображение](https://user-images.githubusercontent.com/393611/186719484-e0fb470d-ae27-4fcf-a6cf-aa578f48cfa1.png)

when I try to create and verify account with such code:

```ruby
rodauth.create_account(login: 'admin6@example.com', password: 'admin6')
rodauth.verify_account(account_login: 'admin2@example.com', password: 'admin6')
```

... this part of code 
https://github.com/jeremyevans/rodauth/blob/90ad8052661c55f8cc394bb36b38b48ddf65899f/lib/rodauth/features/verify_account.rb#L98-L99

just checks that user already logged in and then does not perform any verification code 😞.

**Comment by jeremyevans** [comment]
Any chance you could submit a failing spec for this?  We have specs where `:account_login` and `:password` are both provided, and verification works (https://github.com/jeremyevans/rodauth/blob/master/spec/verify_account_spec.rb#L411), so I'm not sure what is going wrong in your case.

**Comment by mainameiz** [comment]
This was an issue in our application code. Sorry 😞
