### ISSUE TITLE
Notes

### ISSUE THREAD

**Issue by steakknife** [jeremyevans/rodauth#261]
Interesting project. I was looking to implement WebAuthn SSO at home using a FIDO2 solution.

### Security tokens

I was having a look around and noticed JWT.

[PASETO](https://paseto.io) vs. [JW[TES]](https://jwt.io)

- https://paragonie.com/blog/2017/03/jwt-json-web-tokens-is-bad-standard-that-everyone-should-avoid

- https://paseto.io

**Comment by jeremyevans** [comment]
Thank you for your input.  Rodauth does not require JWT (you can use the JSON API without JWT), but it does support JWT.  This is not a bug in Rodauth, so I'm closing this.

**Comment by steakknife** [comment]
Not a bug, but a consideration. :) Also, have you had a look at PAKE protocols such as [OPAQUE](https://blog.cryptographyengineering.com/2018/10/19/lets-talk-about-pake/)?

**Comment by janko** [comment]
@steakknife Considerations should be posted on GitHub discussions, not issues 😉. Issues are for bug reports that have a specific solution, issues' open/close state doesn't work well for discussions.

**Comment by steakknife** [comment]
I didn't even know you had issues enabled. :D

Cool.

**Comment by steakknife** [comment]
* ;)
