### ISSUE TITLE
Documentation Request regarding Active Record

### ISSUE THREAD

**Issue by brandondrew** [jeremyevans/rodauth#282]
Rodauth looks awesome, and thank you for making it possible to integrate with Rails!

However there are a couple of questions that stand out to anyone using Rails:  

* do I have to use Sequel with Rodauth?
* if so, will it conflict with using Active Record in the rest of my app?

The reasons I ask are:

* the README doesn't mention Active Record anywhere, although it does have a statement that could be interpreted as meaning you  must use Sequel (and possibly also that Sequel is your main or your only ORM)
* The examples you provide use Sequel: 
  * https://github.com/jeremyevans/ginatra/commit/28108ebec96e8d42596ee55b01c3f7b50c155dd1 
  * https://github.com/davydovanton/grape-rodauth/blob/master/Gemfile

**Comment by jeremyevans** [comment]
You probably want to ask this question on the rodauth-rails discussion forum: https://github.com/janko/rodauth-rails/discussions/new

To be brief, Rodauth is build on top of Roda and Sequel.  While Rodauth uses Sequel for database access, you don't other have to use Sequel in your application, even if your application uses ActiveRecord.  Sequel should not conflict with ActiveRecord.  By default, the two are independent, though rodauth-rails and related libraries allow for some integration.
