### ISSUE TITLE
Is there way to disable all mail?

### ISSUE THREAD

**Issue by Set27** [jeremyevans/rodauth#344]
If i don't want to confirm new account via email, is there built-in method to disable it?

**Comment by jeremyevans** [comment]
By default the create_account feature doesn't send email.  You have to be using verify_account feature to send email.  So if you don't want to send email, I recommend using create_account and not verify_account.

As mentioned in the contribution guidelines, please only use GitHub Issues to report a bug in Rodauth.  For general questions, ask the question in GitHub Discussions.
