### ISSUE TITLE
after_login_failure

### ISSUE THREAD

**Issue by marshallmick007** [jeremyevans/rodauth#36]
Currently, the `after_login_failure` hook is only fired if the account exists but the password was inaccurate. I would like to log all failed attempts, including those which user names do not exist, which would require the hook to be added to the `unless account_from_login` conditional. However this would leave the `account` property nil for any existing implementations, so the logging example in the docs, if anyone used it, would fail.

Have you thought about this idea at all? My basic use case would be to analyze IP addresses of all failed logins to attempt to identify clients fishing for information, or trying to attack the site.

Perhaps a new hook for the `after_login_not_exist`?

**Comment by jeremyevans** [comment]
I don't think it makes sense to add a hook for this. First, it invites the slippery slope, since there are many other places where such hooks could possibly be useful in certain cases.  Second, you can already use the login_error_flash configuration method to do what you want:

```ruby
  login_error_flash do
    # called for all login failures
    super
  end
```
