### ISSUE TITLE
Two Factor authentication issue: "undefined method `[]' for nil:NilClass"

### ISSUE THREAD

**Issue by jgthms** [jeremyevans/rodauth#389]
Hi and thanks for creating this library.

I am developing an app with both a `main` account type, and an `admin` one. I've succesfully followed [these instructions](https://github.com/janko/rodauth-rails/wiki/Account-Types) to create both account types.

After finalising all the website features, I decided to reset the database with `rake db:reset` to see how the app would behave on a fresh install.

After creating a new `admin` account, I'm running into this error:
![image](https://github.com/jeremyevans/rodauth/assets/1254808/fb0e6814-62a1-4eea-848b-ec44fc64547d)

My `rodauth_admin.rb` configuration looks like this:
![image](https://github.com/jeremyevans/rodauth/assets/1254808/fe8d0428-7905-416c-9845-e94de937a5d4)

Did I miss a step somewhere?

**Comment by jgthms** [comment]
My `rodauth_app.rb` configuration is:

```rb
class RodauthApp < Rodauth::Rails::App
  # primary configuration
  configure RodauthMain

  # secondary configuration
  configure RodauthAdmin, :admin

  route do |r|
    rodauth.load_memory # autologin remembered users

    r.rodauth # route rodauth requests

    # ==> Authenticating requests
    # Call `rodauth.require_account` for requests that you want to
    # require authentication for. For example:
    #
    # # authenticate /dashboard/* and /account/* requests
    # if r.path.start_with?("/dashboard") || r.path.start_with?("/account")
    #   rodauth.require_account
    # end

    # ==> Secondary configurations
    r.rodauth(:admin) # route admin rodauth requests

    if request.path.start_with?("/admin")
      rodauth(:admin).require_account
    end

    # require MFA if the user is logged in and has MFA setup
    if rodauth(:admin).uses_two_factor_authentication?
      rodauth(:admin).require_two_factor_authenticated
    end
  end
end
```

**Comment by jeremyevans** [comment]
You appear to be using rodauth-rails, so please open a discussion in the rodauth-rails repository: https://github.com/janko/rodauth-rails/discussions/new/choose

Only post an issue here if you can reproduce the bug in Rodauth itself (without rodauth-rails).

**Comment by jgthms** [comment]
Sorry! Wrong repo indeed.
