### ISSUE TITLE
Help with using the Phone number instead of Email

### ISSUE THREAD

**Issue by Azzawie** [jeremyevans/rodauth#439]
Sorry, but this is not an issue. It's a question.
Can I use the roadauth gem, where the user Authenticates with a phone number instead of an Email? If so, could you please provide good resources, links, or documents that explain the process or the steps?

Thanks

**Comment by jeremyevans** [comment]
Rodauth doesn't have built in support for that.  It's possible by using Rodauth configuration methods, but I don't think there is an existing guide for it. You'll want something like:

```ruby
login_column :phone_number
login_uses_email? false

# if using any features that send email
send_email do |email|
  # send SMS to phone number instead of emailing
end
```

In the future, please open a discussion instead of an issue if you are not reporting a bug.
