### ISSUE TITLE
The jwt_refresh feature returns the access token even we set create_account_autologin? to true

### ISSUE THREAD

**Issue by Novtopro** [jeremyevans/rodauth#440]
Hi @jeremyevans thanks for your great work. I'm using rodauth for my Roda application, but I encountered an issue when signing up accounts, here's my application

```ruby
# frozen_string_literal: true

require "roda"

class App < Roda
  plugin :all_verbs
  plugin :json
  plugin :json_parser

  plugin :rodauth do
    enable(
      :verify_account,
      :verify_account_grace_period,
      :login,
      :logout,
      :jwt,
      :jwt_refresh,
      :jwt_cors,
      :create_account,
      :reset_password,
      :change_password,
      :change_login,
      :verify_login_change,
      :close_account
    )

    jwt_secret "secret"
    only_json? true
    use_json? true
    create_account_autologin? false
  end

  route do |r|
    r.rodauth
    r.root do
      "Hello, world!"
    end
  end
end
```
Because I enabled the verify_account feature and set `create_account_autologin?` to false, I was expecting the access token not returned when users `POST /create-account`, however, it was returned. That means users can get the access token and access the protected resources even if the account was not verified.

![CleanShot 2024-09-14 at 21 05 01@2x](https://github.com/user-attachments/assets/0574b933-e8ed-467d-9786-ec877f3573e3)

Could you please take a look?

**Comment by jeremyevans** [comment]
Do you know what the content of that access token is? Since `create_account_autologin? false`, my guess it is doesn't actually include access to anything.  You aren't using `rodauth.require_authentication`, so you aren't protecting anything in your example app.

**Comment by jeremyevans** [comment]
Closing due to lack of response.  If you still believe there is an issue, please provide an example showing that your are requiring authentication and Rodauth is allowing access without authentication.

Note that if you do not want unverified users to have access to protected resources, you definitely do not want to use the `verify_account_grace_period` feature.
