### ISSUE TITLE
Rails 5.1.X integration

### ISSUE THREAD

**Issue by bcotteret** [jeremyevans/rodauth#47]
Hi Jeremy,
I am planning to use roadauth with rails 5.1.
I've tested your demo app, but it is using roda-rails, currently locked to rails 4.2
What would be your advice ?
Thanks.

**Comment by jeremyevans** [comment]
Update it to support Rails 5.1?  This would mostly involve adding a rails51 plugin to https://github.com/jeremyevans/roda-rails, and then only minor version tweaks to the demo add should be needed.
