### ISSUE TITLE
References to "model instance"

### ISSUE THREAD

**Issue by janko-m** [jeremyevans/rodauth#48]
I've noticed that Rodauth documentation still references "model instances" for methods like `#account_from_login` and `#account_from_session`. I remember that earlier Rodauth versions had `Sequel::Model` subclasses and created instances from it, but that it was changed at some point to work with hashes directly.

In that case I was wondering we should use difference terminology instead of "model instances". I wanted to make a PR, but I didn't know what would be the appropriate name. I was thinking "records", but I feel like it isn't suitable for `#new_account` because there the instance isn't a database record yet.

**Comment by jeremyevans** [comment]
You can probably just say hashes instead of model instances, since that is what is used now.

**Comment by janko-m** [comment]
Yeah, that sounds good, I'll make the PR.
