### ISSUE TITLE
Handling custom fields in `create_account` form

### ISSUE THREAD

**Issue by manuca** [jeremyevans/rodauth#50]
Hey Jeremy, I'm using Rodauth for an app and I found myself needing to tweak the `create_account` template, that hasn't been an issue as I used the `create_account_view` setting without any problems to override the template. The issue I'm having is with how I can add validations for those new fields. I first tried hooking to the `before_create_account` callback to run validations on my own fields but due to the way the plugin handles validations with [`throw :rodauth_error`](https://github.com/jeremyevans/rodauth/blob/master/lib/rodauth/features/create_account.rb#L47) my validations are reached only after I satisfy `create_account_view`'s own validations. So I first see validations for some of Rodauth's fields and then when I complete those and submit I see mine  validated.

I'd not only like to add my own validations as right now but also to tweak the order in which they run without interfering with Rodauth's process. It would be also super nice if I had the chance to validate all fields at once instead of one field per HTTP request/response cycle as they are being handled right now.

Thanks

**Comment by jeremyevans** [comment]
Thanks for reaching out. I don't think I want to support configurable order of validations in create_account, but here's a possible way to do most of what you want (untested).

```ruby
new_account do |login|
  v = super(login)
  set_field_error("field", "error message") unless field_is_valid
  v
end

before_create_account do
  if field_error("field")
    set_response_error_status(400)
    throw :rodauth_error
  end
  super()
end
```

Basically, when the account is first created, check for field validity at that point, but don't stop processing.  If there is an error in rodauth's checks, it should show the errors for both your custom field (if any) and for the normal rodauth feature.  If it makes it through rodauth's processing, you can still raise the error for just the bad field.

Rodauth currently only supports one error per field, so processing all validations at once is not possible.  I can understand the desire to validate everything at once, but it would probably significantly complicate things when you consider the way that different rodauth features interact. Consider the create_account and disallow_password_reuse features used in combination.  Do we really want to check all previous hashes (a very expensive operation) if the password and confirm password fields do not match?

For a security-sensitive library like rodauth, I think it is best to keep things simple.  If you really want custom handling, you can override the route and handle things exactly the way you want to.

Hopefully this answers your question.  If not or you have additional questions, please open up a thread on the Google Group (https://groups.google.com/forum/#!forum/rodauth) and we can discuss things there (GitHub Issues should be used to report bugs in the library, per the contribution guidelines).

**Comment by manuca** [comment]
Thanks for the explanation I think it makes sense and your solution might work, will try. 

I'll post to the Google Group the next time. Thanks again.
