### ISSUE TITLE
undefined method 'parse_template_opts' on unlock-account-request with json: :only

### ISSUE THREAD

**Issue by opya** [jeremyevans/rodauth#53]
Hi @jeremyevans , thank you for beautiful roda, and rodauth.

My setup is [roda-sequel-stack](https://github.com/jeremyevans/roda-sequel-stack) + rodauth. I want to build json only api, my app. rb look like this.

```ruby
require_relative 'models'
require 'roda'
require 'rodauth'
require 'mail'

Unreloader.require('config')

class SkateSpot < Roda
  MAILS = {}
  MUTEX = Mutex.new
  ::Mail.defaults do
    delivery_method :test
  end

  plugin :i18n, locale: [:bg, :en], default_locale: :bg
  plugin :default_headers, DEFAULT_HEADERS
  plugin :multi_route
  plugin :all_verbs
  plugin :not_allowed
  plugin :hooks
  plugin :symbol_status
  plugin :not_found do |a|
    "File Not Found " + a.to_s
  end
  # TODO: add when email is setup
  #   plugin :error_mail, to: 'to@example.com', from: 'from@example.com'
  plugin :error_handler do |e|
    "Oh No!" + e.message
    #TODO
    # error_mail(e)
  end
  plugin :rodauth, json: :only do
    enable  :create_account,
            :login,
            :logout,
            :change_password,
            :lockout,
            :jwt 

    Jwt.config(self)
  end

  Unreloader.require('routes')

  after do
    Mail::TestMailer.deliveries.each do |mail|
      MUTEX.synchronize{MAILS[rodauth.session_value] = mail}
    end
    Mail::TestMailer.deliveries.clear
  end

  route do |r|
    r.i18n_set_locale_from(:params)
    r.multi_route
    r.rodauth

    r.root do
      Time.now.to_i.to_s
    end
  end
end
```

and rodauth configs

```ruby
class Jwt
  def self.config(config)
    config.jwt_secret ENV['JWT_SECRET']
    config.jwt_session_key 'data'
    config.jwt_symbolize_deeply? true
    config.json_response_success_key 'success'
    config.json_response_custom_error_status? true
    config.jwt_session_hash do
      h = super()
      h.merge(
        aud: %w[Young Old],
        exp: Time.now.to_i + 172800,
        iat: Time.now.to_i,
        iss: "https://www.skate-spot.bg",
        jti: SecureRandom.hex(10),
        nbf: Time.now.to_i - 10,
        sub: session_value
      )
    end
    config.jwt_decode_opts(
      aud: 'Old',
      iss: "https://www.skate-spot.bg",
      leeway: 10,
      verify_aud: true,
      verify_expiration: true,
      verify_iat: true,
      verify_iss: true,
      verify_jti: true,
      verify_not_before: true
    )
    config.max_invalid_logins 5
    config.email_from 'opya@localhost'
  end
end
```

```ruby
DEFAULT_HEADERS = {
  'Content-Type'=>'application/json',
  'X-Frame-Options'=>'deny',
  'X-Content-Type-Options'=>'nosniff',
  'X-XSS-Protection'=>'1; mode=block'
  #'Strict-Transport-Security'=>'max-age=16070400;', # Uncomment if only allowing https:// access
}
```

Thre problem is when try to unlock user

`curl -X POST http://127.0.0.1:9292/unlock-account-request --header 'Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJkYXRhIjp7ImFjY291bnRfaWQiOjd9LCJhdWQiOlsiWW91bmciLCJPbGQiXSwiZXhwIjoxNTMzODA0NDkxLCJpYXQiOjE1MzM2MzE2OTEsImlzcyI6Imh0dHBzOi8vd3d3LnNrYXRlLXNwb3QuYmciLCJqdGkiOiIyODkzNmEwZTEzZDJmOTNlMDM0ZSIsIm5iZiI6MTUzMzYzMTY4MSwic3ViIjo3fQ.wyCmN9i3-rsoO9rKLVRGNmDujR5XFLESxCJBSzVH4ME' --header 'Content-Type: application/json'  --data '{"login":"chepashnikow@gmail.com"}'`

and it breaks with:

`Oh No!undefined method 'parse_template_opts' for #<SkateSpot:0x0000000333bac8>`

I dig a bit and found that, when sending mail with unlock token [lockout.rb](https://github.com/jeremyevans/rodauth/blob/33996416714a5a222fc61d6090ed32ae3775b42b/lib/rodauth/features/lockout.rb#L258). Because i'm use json: :only and render plugin is not added [rodauth.rb](https://github.com/jeremyevans/rodauth/blob/33996416714a5a222fc61d6090ed32ae3775b42b/lib/rodauth.rb#L15) i'm sure I miss something.

Thanks :)

**Comment by jeremyevans** [comment]
As stated in the README (http://rodauth.jeremyevans.net/rdoc/files/README_rdoc.html#label-Plugin+Options), if you are using `json: :only` and also using features that send email, you need to add the render plugin manually to the Roda app.  That should fix this problem.

**Comment by opya** [comment]
Thanks :)
