### ISSUE TITLE
demo-site errors

### ISSUE THREAD

**Issue by jots** [jeremyevans/rodauth#58]
New to rodauth, I tried to run the demo-site and received errors like:
```
 undefined method `mark_input_fields_as_required?' for #<Rodauth::Configuration
```
had to comment out these lines from rodauth_demo.rb to make it run:
```
    mark_input_fields_as_required? true
    login_input_type 'email'
    jwt_secret(secret)
    hmac_secret secret
```
not sure if an error with my config.

**Comment by jeremyevans** [comment]
The demo site currently requires the master branch, not just the latest release.  The next release should be out by mid-June.  You should be able to get the demo site running going to the demo site directory and doing `rackup -I ../lib` (or similar method to include the repository lib directory in the ruby library path).

**Comment by jots** [comment]
Thank you Jeremy!  TIL `rackup -I` which worked perfectly.
