### ISSUE TITLE
#authenticated? returns false when on the OTP setup page

### ISSUE THREAD

**Issue by janko** [jeremyevans/rodauth#68]
Let's say I have the following logic in my navigation: if "authenticated", display a logout link, otherwise display login & create account links.

In my application I'm using `rodauth.authenticated?` for this conditional, because I'm requiring 2FA if it's been setup (via `rodauth.require_authentication`). If I used `rodauth.logged_in?`, then at the step of entering the 2FA code (after successful login) my navigation would indicate that the user is already signed in, which would be incorrect as they still need to enter the 2FA code.

Given the user is logged in but his account doesn't yet have 2FA setup, when they visit the OTP setup page, then `rodauth.authenticated?` returns false. The reason for this is that the `rodauth.two_factor_authentication_setup?` method (which `rodauth.authenticated?` calls) checks whether the OTP key exists, which it does because visting the 2FA page generates a temporary OTP key.

I think this is probably a bug, because I would expect `rodauth.two_factor_authentication_setup?` to return true only after the setup has been completed (i.e. the user has entered the 2FA code on the OTP setup page). In my case this results in the navigation appearing as if though the user is not authenticated when the user is on the OTP setup page.

**Comment by jeremyevans** [comment]
Thanks for the report. I think you are correct, that `two_factor_authentication_setup?` should not return true for a temporary OTP key, only for an actual OTP key.  Can you send in a pull request with a spec for this change?  If not, I can work on it next week.

**Comment by janko** [comment]
Yes, I already got pretty familiar with the 2FA code, so I should be able to send in a pull request 👍

**Comment by janko** [comment]
I'm currently got busy preparing a Sequel talk for our local Ruby meetup here in Brno, Czech Republic, so at the moment I'm not able to find time to create a fix. If you want feel free to take over, otherwise I'll let you know when my time frees up and I'm able to pick it up again.

**Comment by jeremyevans** [comment]
Not a problem, I think I'll be able to work on a fix in the next few days.  Best of luck with your talk.
