### ISSUE TITLE
email_auth with verify_account_grace_period feature

### ISSUE THREAD

**Issue by janko** [jeremyevans/rodauth#88]
When email_auth feature is used with verify_account_grace_period feature, and the account is in the unverified grace period, an email auth request can be sent, but when the user opens the email link, they will see an error that the email auth key is invalid.

This is because the `#account_from_email_auth_key` method adds an open status requirement to the query filter, without verify_account_grace_period feature overriding it anywhere.

I was thinking of extracting the open status filter in `#account_from_key` into a separate method that verify_account_grace_period could override, but that method is used for other status values as well. So I'm not sure what would be a good fix for that 🤔

**Comment by jeremyevans** [comment]
We shouldn't send an email auth email if the account is not verified.  We'll need to add a method to the `email_auth` feature, use it in `_multi_phase_login_forms`, and override the method in the `verify_account_grace_period` feature.

**Comment by janko** [comment]
Ok, thanks for the pointers, I will try to work on this tomorrow.

**Comment by jeremyevans** [comment]
Actually, I've already implemented this locally.  Should be pushed up in a bit after testing finishes.

**Comment by janko** [comment]
Awesome, thank you!
