### ISSUE TITLE
Return a custom hash

### ISSUE THREAD

**Issue by arthurmmoreira** [jeremyevans/rodauth#93]
Hello.

I'm using roda and rodauth in my api and I want to customize responses (successes and errors) handled by rodauth. I couldn’t find a way to do that. I know it’s possible to customize each error message and each error status, but can I return a custom hash?

Thanks

**Comment by jeremyevans** [comment]
`json_response` can be used in one of the rodauth configuration method blocks to access the response hash that will be returned to the user.  Will that work for you?

**Comment by arthurmmoreira** [comment]
Yes, I can use `json_response` to access the response hash and use `json_response_*` methods provided by jwt feature to customize successes and errors keys. But I cannot, for example, return a hash like this ```{ response: { ok: true, success: "You have been logged in" } }```.

But it's ok.

Thanks for your help.

**Comment by janko** [comment]
Correct me if I'm wrong, but I believe you can use `json_response_body` for that:

```rb
json_response_body do |hash| # yields the json_response hash
  { response: hash }.to_json
end
```

**Comment by arthurmmoreira** [comment]
Yes, I can use the method `json_response_body` to customize my hash.

Thanks.
