### ISSUE TITLE
valid http basic auth should be logged_in?

### ISSUE THREAD

**Issue by HoneyryderChuck** [jeremyevans/rodauth#94]
According to my expectation, `logged_in?` with a valid Authorization header and the http basic auth should be true, however it is not.

The method isn't overwritten in the respective plugin, in fact, require_login is the reworked method, which is only working well for browser flows where the error will come in a cookie and response returns 302.

**Comment by jeremyevans** [comment]
Starting in Rodauth 2.0, you need to call `rodauth.http_basic_auth` in your routing tree to load authentication information from HTTP Basic Authentication.  Once you call that method, `rodauth.logged_in?` should be true if the HTTP Basic Authentication information is valid.  Can you try that?

**Comment by HoneyryderChuck** [comment]
just tried, and it works. However, I don't find it very intuitive, as I'm used to consider `r.rodauth` as the beginnning of the rodauth journey, even the most basic tutorial refers to it that way. Can I ask what was the reason for changing it? I get the defining `session` might have been too much, but `logged_in?` or something like it could have made sense.

Otherwise, feel free to close it, thx for the help.

**Comment by jeremyevans** [comment]
I suppose we could override `logged_in` to call `http_basic_auth` if `super` returns false, then retry the `super` call.  Do you think that would work?

You are correct that overriding `session` was considered too extreme, and that was the reason behind the change.  Now the `http_basic_auth` feature works similarly to the `remember` feature (which uses `rodauth.load_memory` to load auth information from a cookie).

**Comment by HoneyryderChuck** [comment]
I agree with your proposal, overriding logged_in? would make sense.

**Comment by jeremyevans** [comment]
OK.  I'll try to work on that tomorrow.

**Comment by HoneyryderChuck** [comment]
thx @jeremyevans
