### ISSUE TITLE
Remove trailing slash from rodauth requests

### ISSUE THREAD

**Issue by arthurmmoreira** [jeremyevans/rodauth#95]
Is there any way to remove the trailing slash from rodauth requests?
When I use `slash_path_empty` plugin from Roda, it doesn't work with the rodauth requests.

**Comment by jeremyevans** [comment]
Not sure what you mean.  Rodauth doesn't use trailing slashes in requests.  For example, the default login path is `/login`, not `/login/`

**Comment by arthurmmoreira** [comment]
Yes, I know. But I want to consider `/login` and `/login/` a valid login path.
I tried `slash_path_empty` from roda, but it didn't work with rodauth's paths. Is there a way to consider both options?

**Comment by jeremyevans** [comment]
Either before or after `r.rodauth`:

```ruby
r.get "login/" do
  r.redirect "/login"
end
```

You can expand this approach for other rodauth routes you are using. I assume you only need the GET request redirect, since the page itself will use the correct path for the POST request.

**Comment by arthurmmoreira** [comment]
This redirect will not work for me.
My application is an api and the request finishes when I redirect a POST request (I know it's by design). Is there something else I should try?

**Comment by jeremyevans** [comment]
I guess I don't understand the issue completely.  If you have an API, you should be able to expect that people use the correct paths (unlike a browser based app, where users can type paths into the address bar).

You can try using Roda's path_rewriter plugin to rewrite the path:

```ruby
class App < Roda
  plugin :path_rewriter
  rewrite_path "/login/", "/login"
  # ...

  plugin :rodauth do
    # ...
  end

  # ...
end
```

**Comment by arthurmmoreira** [comment]
Ok, I think it will work. Thanks for your help.

**Comment by okliv** [comment]
````ruby
r.get(/(.*)\/+$/) { |path| r.redirect "/#{path}", 301 }
